SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_ID, LOCATION_ID FROM DEPARTMENTS;
SELECT SALARY , SALARY + 30 FROM EMPLOYEES;
SELECT last_name, salary, 12*salary+100
FROM employees;

SELECT 500, 12*500+100 FROM DUAL;
SELECT 500, 12*(500+100) FROM DUAL;

SELECT 500, 12*500+100,12*(500+100)  FROM DUAL;
SELECT commission_pct FROM EMPLOYEES;
SELECT commission_pct FROM EMPLOYEES WHERE commission_pct IS NOT NULL;

SELECT 100 + NULL FROM DUAL;

SELECT SALARY, SALARY + 100 FROM EMPLOYEES;

SELECT DISTINCT commission_pct FROM EMPLOYEES ORDER BY commission_pct DESC;

SELECT 500, 12*500+100,12*(500+100) AS "COMPUTED VALUE"  FROM DUAL;
SELECT 500, 12*500+100,12*(500+100)  "COMPUTED VALUE"  FROM DUAL;
SELECT 500, 12*500+100,12*(500+100) COMPUTED  FROM DUAL;
SELECT 500, 12*500+100,12*(500+100) AS COMPUTED  FROM DUAL;

SELECT 500, 12*500+100,12*(500+100) AS COMPUTED VALUE  FROM DUAL;
SELECT 500, 12*500+100,12*(500+100)  COMPUTED VALUE  FROM DUAL;

SELECT  FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT  'MR/MRS/MS/MASTER :  ' || FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT  'MR/MRS/MS/MASTER :  ' + FIRST_NAME, LAST_NAME FROM EMPLOYEES;

select q'[You are a wonderful trainer... isn't it?]' from dual;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;
SELECT COUNT (JOB_ID) FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT (DISTINCT JOB_ID) FROM EMPLOYEES;

DESCRIBE EMPLOYEES;

SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID < 106;
SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 103 !=  106;

SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID = 106;
SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID != 106 ;
SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID <> 106;
SELECT *FROM EMPLOYEES WHERE EMPLOYEE_ID <><> 106;
SELECT *FROM EMPLOYEES WHERE NOT EMPLOYEE_ID = 106;

SELECT *FROM EMPLOYEES WHERE  EMPLOYEE_ID NOT BETWEEN 101 AND 500;
SELECT *FROM EMPLOYEES WHERE  NOT EMPLOYEE_ID  BETWEEN 101 AND 500;
SELECT *FROM EMPLOYEES WHERE MANAGER_ID IN (100,102);

SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%SS%';
SELECT * FROM EMPLOYEES WHERE LAST_NAME LIKE '%ss%';
SELECT * FROM EMPLOYEES WHERE upper(LAST_NAME) LIKE '%SS%';
SELECT * FROM EMPLOYEES WHERE lower(LAST_NAME) LIKE '___n';
SELECT * FROM EMPLOYEES WHERE lower(LAST_NAME) LIKE '___n'
or  lower(LAST_NAME) LIKE '___r' ;

SELECT JOB_ID, FIRST_NAME FROM EMPLOYEES
ORDER BY JOB_ID DESC, FIRST_NAME DESC;

SELECT employee_id, last_name, salary, department_id
FROM employees
WHERE employee_id = &EnterEmployeeID ;

